import JinWishartFormalization.TwoRowOutageScaling
import JinWishartFormalization.TwoRowSampleCoordinates
import JinWishartFormalization.TwoRowMeanGramSpectrum

/-!
# Single-stream paper scaling in the actual `2 × 1` model

For `s=1`, `t=2`, the paper's physical channel has the form
`H = ε (√K H̄ + H̃)`. The Wishart eigenvalue `φ` is the eigenvalue of the
unit-scatter Gram matrix generated by `H̃ + √K H̄`, and its SNR is
`ε² P φ = P φ/(K+1)`. This module makes that parameter substitution explicit
and transfers the actual `2 × 1` hard-edge asymptotic to a high-`P` outage limit.

The normalization hypothesis on `H̄` is written as its squared Frobenius norm
`∑ ‖H̄ᵢ₀‖² = 2`, the `2 × 1` form of `tr(H̄ H̄ᴴ)=2`.
-/

open Filter MeasureTheory ProbabilityTheory Topology

namespace JinWishart

noncomputable section

/-- Scattering standard deviation `ε=(K+1)^{-1/2}` in the paper's channel
model. -/
def paperScatterEpsilon (K : ℝ) : ℝ := Real.sqrt ((K + 1)⁻¹)

theorem paperScatterEpsilon_sq (K : ℝ) (hK : 0 ≤ K) :
    paperScatterEpsilon K ^ 2 = (K + 1)⁻¹ := by
  rw [paperScatterEpsilon, Real.sq_sqrt]
  positivity

/-- For one active stream, the paper's SNR multiplier `ε²P` is exactly
`P/(K+1)`. -/
theorem paperSingleStreamSNRScale_eq
    (K P : ℝ) (hK : 0 ≤ K) :
    paperScatterEpsilon K ^ 2 * P = P / (K + 1) := by
  rw [paperScatterEpsilon_sq K hK]
  simp [div_eq_mul_inv, mul_comm]

/-- The physical `2 × 1` mean `ε √K H̄` appearing before division by the
scattering scale. -/
def paperPhysicalTwoRowMean (K ε : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ) :
    Matrix (Fin 2) (Fin 1) ℂ :=
  (ε : ℂ) • ((Real.sqrt K : ℂ) • Hbar)

/-- The actual unit-scatter noncentral mean after the paper's `ε` normalization.
The equality theorem below shows that this is exactly `√K H̄`. -/
def paperNormalizedTwoRowMean (K ε : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ) :
    Matrix (Fin 2) (Fin 1) ℂ :=
  (ε : ℂ)⁻¹ • paperPhysicalTwoRowMean K ε Hbar

theorem paperNormalizedTwoRowMean_eq
    (K ε : ℝ) (hε : ε ≠ 0) (Hbar : Matrix (Fin 2) (Fin 1) ℂ) :
    paperNormalizedTwoRowMean K ε Hbar = (Real.sqrt K : ℂ) • Hbar := by
  rw [paperNormalizedTwoRowMean, paperPhysicalTwoRowMean, smul_smul]
  have hscalar : (ε : ℂ)⁻¹ * (ε : ℂ) = 1 := by
    have hεC : (ε : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr hε
    exact inv_mul_cancel₀ hεC
  rw [hscalar]
  simp

/-- The paper's one-stream outage event, represented by its unit-scatter
Wishart eigenvalue and the exact scale `ε²P = P/(K+1)`. -/
def paperTwoRowWeakOutageProbability
    (K P γ : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ) : ENNReal :=
  weakOutageProbability
    (stdGaussian (ComplexSample (m := 2) (n := 1)))
    (complexNoncentralSampleSmallestEigenvalue
      ((Real.sqrt K : ℂ) • Hbar) (by norm_num))
    (P / (K + 1)) γ

/-- The normalized mean and SNR scale used in the outage definition are
precisely the paper's physical mean divided by `ε` and the `ε²P` multiplier. -/
theorem paperTwoRowWeakOutageProbability_eq_physicalParameters
    (K P γ ε : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ)
    (hε : 0 < ε)
    (hεsq : ε ^ 2 = (K + 1)⁻¹) :
    paperTwoRowWeakOutageProbability K P γ Hbar =
      weakOutageProbability
        (stdGaussian (ComplexSample (m := 2) (n := 1)))
        (complexNoncentralSampleSmallestEigenvalue
          (paperNormalizedTwoRowMean K ε Hbar) (by norm_num))
        (ε ^ 2 * P) γ := by
  rw [paperTwoRowWeakOutageProbability, paperNormalizedTwoRowMean_eq K ε
    (ne_of_gt hε) Hbar]
  congr 2
  rw [hεsq]
  simp [div_eq_mul_inv, mul_comm]

/-- Exact single-stream threshold conversion: the SNR scale is
`ε²P=P/(K+1)`, and the resulting probability is the unit-scatter Wishart
CDF at the divided threshold. -/
theorem paperTwoRowWeakOutage_eq_normalizedCDF
    (K P γ : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ)
    (hK : 0 ≤ K) (hP : 0 < P) :
    (paperTwoRowWeakOutageProbability K P γ Hbar).toReal =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue
          ((Real.sqrt K : ℂ) • Hbar) (by norm_num))) (γ / (P / (K + 1))) := by
  unfold paperTwoRowWeakOutageProbability
  apply twoRowWeakOutage_to_actualCDF
  exact div_pos hP (by linarith)

/-- Under the paper's trace normalization, the `2 × 1` noncentral parameter in
the actual CDF is exactly `‖complexSampleMean(√K H̄)‖²/2 = 2K`. -/
theorem paperTwoRow_noncentrality_eq_twoK
    (K : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ)
    (hK : 0 ≤ K) (hHbar : ∑ i : Fin 2, ‖Hbar i 0‖ ^ 2 = 2) :
    ‖complexSampleMean ((Real.sqrt K : ℂ) • Hbar)‖ ^ 2 / 2 = 2 * K := by
  rw [twoRowComplexMean_norm_sq_div_two]
  have henergy :
      ∑ i : Fin 2, ‖((Real.sqrt K : ℂ) • Hbar) i 0‖ ^ 2 = 2 * K := by
    change ∑ i : Fin 2, ‖(Real.sqrt K : ℂ) * Hbar i 0‖ ^ 2 = 2 * K
    simp_rw [Complex.norm_mul, Complex.norm_real,
      Real.norm_eq_abs, abs_of_nonneg (Real.sqrt_nonneg K)]
    simp_rw [mul_pow]
    rw [← Finset.mul_sum]
    rw [hHbar]
    rw [Real.sq_sqrt hK]
    ring
  exact henergy

/-- Exact `2 × 1`, single-stream high-SNR outage coefficient. It is the
paper's `r=1`, `st=2` low-outage expression after substituting
`ε²=(K+1)⁻¹`, `tr(H̄H̄ᴴ)=2`, and the actual unit-scatter mean `√K H̄`. -/
theorem paperTwoRowWeakOutage_highSNR_limit
    (K γ : ℝ) (Hbar : Matrix (Fin 2) (Fin 1) ℂ)
    (hK : 0 ≤ K) (hγ : 0 < γ)
    (hHbar : ∑ i : Fin 2, ‖Hbar i 0‖ ^ 2 = 2) :
    Tendsto (fun P : ℝ => P ^ 2 *
      (paperTwoRowWeakOutageProbability K P γ Hbar).toReal)
      atTop (𝓝 ((K + 1) ^ 2 * γ ^ 2 * (1 / 2) * Real.exp (-2 * K))) := by
  let M : Matrix (Fin 2) (Fin 1) ℂ := (Real.sqrt K : ℂ) • Hbar
  let scale : ℝ → ℝ := fun P => P / (K + 1)
  have hscalePos : 0 < K + 1 := by linarith
  have hscaleTop : Tendsto scale atTop atTop := by
    apply Filter.tendsto_atTop.2
    intro b
    filter_upwards [eventually_gt_atTop ((K + 1) * b)] with P hP
    apply le_of_lt
    apply (lt_div_iff₀ hscalePos).2
    simpa [mul_comm] using hP
  have hactual := twoRowWeakOutage_highScale_limit M γ hγ
  have hscaled := hactual.comp hscaleTop
  have hnoncentral : ‖complexSampleMean M‖ ^ 2 / 2 = 2 * K := by
    dsimp [M]
    exact paperTwoRow_noncentrality_eq_twoK K Hbar hK hHbar
  have hconst : Tendsto (fun P : ℝ => (K + 1) ^ 2 *
      (scale P ^ 2 * (paperTwoRowWeakOutageProbability K P γ Hbar).toReal))
      atTop (𝓝 ((K + 1) ^ 2 * (γ ^ 2 * ((1 / 2) * Real.exp (-2 * K))))) := by
    have hscaled' : Tendsto (fun P : ℝ => scale P ^ 2 *
        (paperTwoRowWeakOutageProbability K P γ Hbar).toReal)
        atTop (𝓝 (γ ^ 2 * (1 / 2 * Real.exp (-2 * K)))) := by
      have hEq : (fun P : ℝ => scale P ^ 2 *
          (paperTwoRowWeakOutageProbability K P γ Hbar).toReal) =ᶠ[atTop]
          (fun P => scale P ^ 2 *
            (weakOutageProbability
              (stdGaussian (ComplexSample (m := 2) (n := 1)))
              (complexNoncentralSampleSmallestEigenvalue M (by norm_num))
              (scale P) γ).toReal) := by
        filter_upwards with P
        simp [paperTwoRowWeakOutageProbability, M, scale]
      have hlim := hscaled.congr' hEq.symm
      simpa [hnoncentral] using hlim
    exact tendsto_const_nhds.mul hscaled'
  have hEq : (fun P : ℝ => P ^ 2 *
      (paperTwoRowWeakOutageProbability K P γ Hbar).toReal) =ᶠ[atTop]
      (fun P => (K + 1) ^ 2 *
        (scale P ^ 2 * (paperTwoRowWeakOutageProbability K P γ Hbar).toReal)) := by
    filter_upwards with P
    dsimp [scale]
    field_simp [ne_of_gt hscalePos]
  have hconst' := hconst.congr' hEq.symm
  simpa [mul_assoc] using hconst'

end

end JinWishart
