import JinWishartFormalization.TwoRowSampleCoordinates
import JinWishartFormalization.Theorem1TwoRowsNoncentral
import JinWishartFormalization.WishartGamma
import Mathlib.Probability.CDF

/-!
# Theorem 1 in the actual axial `2 × 1` noncentral Wishart model

The formula-side specialization is now connected to the CDF of the Gram
eigenvalue generated by the repository's complex Gaussian sample space.
-/

open MeasureTheory ProbabilityTheory Set

namespace JinWishart

/-- In the `2 × 1` sample orientation, the Gram matrix is `1 × 1`, so its
unique eigenvalue is its largest eigenvalue. This names that statistic
explicitly instead of silently identifying it with the smallest-eigenvalue
API. -/
noncomputable def twoRowUniqueGramEigenvalue
    (M : Matrix (Fin 2) (Fin 1) ℂ)
    (z : ComplexSample (m := 2) (n := 1)) : ℝ :=
  (complexGram_posSemidef (complexSampleMatrix z + M)).1.eigenvalues₀ 0

theorem complexNoncentralSampleSmallestEigenvalue_eq_twoRowUniqueGramEigenvalue
    (M : Matrix (Fin 2) (Fin 1) ℂ)
    (z : ComplexSample (m := 2) (n := 1)) :
    complexNoncentralSampleSmallestEigenvalue M (by norm_num) z =
      twoRowUniqueGramEigenvalue M z := by
  have hidx : smallestEigenvalue₀Index (n := 1) (by norm_num) =
      (0 : Fin (Fintype.card (Fin 1))) := by
    apply Fin.ext
    simp [smallestEigenvalue₀Index]
  simp [complexNoncentralSampleSmallestEigenvalue, twoRowUniqueGramEigenvalue,
    hidx]

/-- The actual two-row, one-column noncentral CDF depends on the deterministic
complex mean only through the norm of its real Gaussian coordinate vector. -/
theorem noncentralTwoRowCDF_eq_meanNormNuttallQ
    (M : Matrix (Fin 2) (Fin 1) ℂ) (x : ℝ) (hx : 0 ≤ x)
    (hM : complexSampleMean M ≠ 0) :
    cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue M (by norm_num))) x =
      1 - (nuttallQ 2 1 ‖complexSampleMean M‖ (Real.sqrt (2 * x)) /
        (‖complexSampleMean M‖ : ℂ)).re := by
  rw [cdf_eq_real, measureReal_def]
  rw [noncentralColumnSmallestEigenvalue_sublevelMass_eq_shiftedBall
    (m := 2) (by norm_num) M x hx]
  have hball :
      (stdGaussian (ComplexSample (m := 2) (n := 1)))
          (Metric.closedBall (-complexSampleMean M) (Real.sqrt (2 * x))) =
        (stdGaussian (EuclideanSpace ℝ (Fin 4)))
          (Metric.closedBall
            (-(twoRowSampleToFin4 (complexSampleMean M))) (Real.sqrt (2 * x))) := by
    rw [← stdGaussian_map_twoRowSampleToFin4]
    rw [Measure.map_apply (twoRowSampleToFin4.continuous.measurable)
      measurableSet_closedBall]
    rw [twoRowSampleToFin4.preimage_closedBall
      (-(twoRowSampleToFin4 (complexSampleMean M))) (Real.sqrt (2 * x))]
    simp
  rw [hball, ← measureReal_def]
  simpa only [twoRowSampleToFin4.norm_map] using
    (stdGaussian_fourDBall_anyMean_eq_one_sub_nuttallQ21
    (twoRowSampleToFin4 (complexSampleMean M))
    (by simpa using hM) (Real.sqrt (2 * x)) (Real.sqrt_nonneg _))

private theorem nuttallQ21_eq_realIntegral (a b : ℝ) (ha : 0 ≤ a)
    (hb : 0 ≤ b) :
    nuttallQ 2 1 a b =
      (∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) := by
  have hint : IntegrableOn (fun t : ℝ => nuttallQIntegrand 2 1 a t)
      (Ioi b) :=
    (nuttallQ21Integrand_integrableOn_Ioi a ha).mono_set
      (Ioi_subset_Ioi hb)
  unfold nuttallQ
  rw [← integral_complex_ofReal]
  apply setIntegral_congr_fun measurableSet_Ioi
  intro t _
  exact nuttallQ21Integrand_eq_realKernel a t

/-- For nonnegative amplitude and threshold, the complex Q tail is the
nonnegative real Bessel-kernel tail. -/
private theorem norm_nuttallQ21_eq_realIntegral (a b : ℝ) (ha : 0 ≤ a)
    (hb : 0 ≤ b) :
    ‖nuttallQ 2 1 a b‖ =
      ∫ t in Ioi b, nuttallQ21RealKernel a t := by
  rw [nuttallQ21_eq_realIntegral a b ha hb]
  have hnonneg : 0 ≤ ∫ t in Ioi b, nuttallQ21RealKernel a t :=
    setIntegral_nonneg measurableSet_Ioi fun t ht =>
      nuttallQ21RealKernel_nonneg_of_nonneg ha (le_of_lt (lt_of_le_of_lt hb ht))
  have hcast :
      (∫ t in Ioi b, (nuttallQ21RealKernel a t : ℂ)) =
        ((∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) : ℂ) :=
    integral_complex_ofReal
  calc
    ‖((∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) : ℂ)‖ =
        ‖∫ t in Ioi b, (nuttallQ21RealKernel a t : ℂ)‖ := by
          exact congrArg norm hcast.symm
    _ = ‖((∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) : ℂ)‖ :=
      congrArg norm hcast
    _ = ‖∫ t in Ioi b, nuttallQ21RealKernel a t‖ := Complex.norm_real _
    _ = |∫ t in Ioi b, nuttallQ21RealKernel a t| := Real.norm_eq_abs _
    _ = ∫ t in Ioi b, nuttallQ21RealKernel a t := abs_of_nonneg hnonneg

/-- The paper's Theorem 1 formula for `(s,t,L)=(1,2,1)` is the actual weak CDF
of the smallest eigenvalue of the complex noncentral Wishart sample, for an
axial mean with squared magnitude `lambda`. -/
theorem theorem1TwoRowsCandidate_eq_actualAxialCDF
    (lambda x : ℝ) (hlambda : 0 < lambda) (hx : 0 ≤ x) :
    theorem1CdfCandidate 1 2 1 (by omega) (by omega)
        (fun _ : Fin 1 => lambda) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue
          (twoRowAxialMean (Real.sqrt (2 * lambda))) (by norm_num))) x := by
  let a : ℝ := Real.sqrt (2 * lambda)
  have ha : 0 < a := by
    dsimp [a]
    exact Real.sqrt_pos.2 (by positivity)
  have hax : 0 ≤ Real.sqrt (2 * x) := Real.sqrt_nonneg _
  have hQnorm : ‖nuttallQ 2 1 a (Real.sqrt (2 * x))‖ =
      ∫ t in Ioi (Real.sqrt (2 * x)), nuttallQ21RealKernel a t :=
    norm_nuttallQ21_eq_realIntegral a _ ha.le hax
  have hQratio :
      (nuttallQ 2 1 a (Real.sqrt (2 * x)) / (a : ℂ)).re =
        ‖nuttallQ 2 1 a (Real.sqrt (2 * x))‖ / a := by
    have hreal : (nuttallQ 2 1 a (Real.sqrt (2 * x))).re =
        ‖nuttallQ 2 1 a (Real.sqrt (2 * x))‖ := by
      rw [nuttallQ21_eq_realIntegral a _ ha.le hax, Complex.ofReal_re]
      have hnonneg : 0 ≤ ∫ t in Ioi (Real.sqrt (2 * x)),
          nuttallQ21RealKernel a t :=
        setIntegral_nonneg measurableSet_Ioi fun t ht =>
          nuttallQ21RealKernel_nonneg_of_nonneg ha.le
            (le_of_lt (lt_of_le_of_lt hax ht))
      rw [Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hnonneg]
    rw [Complex.div_ofReal_re]
    exact congrArg (fun y : ℝ => y / a) hreal
  rw [theorem1TwoRowsCandidate_eq_amplitudeNormalizedQ lambda x hlambda]
  rw [noncentralTwoRowAxialCDF_eq_one_sub_nuttallQ21 a x ha hx]
  rw [hQratio]
  dsimp [a, theorem1TwoRowScalarQ]

/-- In the same axial `(1,2,1)` model, the paper's Theorem 2 candidate also
equals the actual CDF.  There is only one Gram eigenvalue, so its largest- and
smallest-eigenvalue CDFs coincide. -/
theorem theorem2TwoRowsCandidate_eq_actualAxialCDF
    (lambda x : ℝ) (hlambda : 0 < lambda) (hx : 0 ≤ x) :
    theorem2CdfCandidate 1 2 1 (by omega) (by omega)
        (fun _ : Fin 1 => lambda) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue
          (twoRowAxialMean (Real.sqrt (2 * lambda))) (by norm_num))) x := by
  let a : ℝ := Real.sqrt (2 * lambda)
  let b : ℝ := Real.sqrt (2 * x)
  have ha : 0 < a := by dsimp [a]; exact Real.sqrt_pos.2 (by positivity)
  have hb : 0 ≤ b := by dsimp [b]; exact Real.sqrt_nonneg _
  have htotal : ∫ t in Ioi (0 : ℝ), nuttallQ21RealKernel a t = a :=
    nuttallQ21RealIntegral_eq_amplitude a ha
  have hmono : ∫ t in Ioi b, nuttallQ21RealKernel a t ≤
      ∫ t in Ioi (0 : ℝ), nuttallQ21RealKernel a t := by
    apply setIntegral_mono_set (nuttallQ21RealKernel_integrableOn_Ioi a ha.le)
      ?_ (Ioi_subset_Ioi hb).eventuallySubset
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    exact nuttallQ21RealKernel_nonneg_of_nonneg ha.le (le_of_lt ht)
  have hQb : nuttallQ 2 1 a b =
      (∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) :=
    nuttallQ21_eq_realIntegral a b ha.le hb
  have hQ0 : nuttallQ 2 1 a 0 = (a : ℂ) :=
    nuttallQ21_zeroThreshold_eq_amplitude a ha
  have hdiff : nuttallQ 2 1 a 0 - nuttallQ 2 1 a b =
      ((a - ∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) : ℂ) := by
    rw [hQ0, hQb]
    push_cast
    rfl
  have hdiff_nonneg : 0 ≤ a - ∫ t in Ioi b, nuttallQ21RealKernel a t := by
    apply sub_nonneg.mpr
    calc
      (∫ t in Ioi b, nuttallQ21RealKernel a t) ≤
          ∫ t in Ioi (0 : ℝ), nuttallQ21RealKernel a t := hmono
      _ = a := htotal
  have hnorm_diff :
      ‖nuttallQ 2 1 a 0 - nuttallQ 2 1 a b‖ =
        a - ∫ t in Ioi b, nuttallQ21RealKernel a t := by
    rw [hdiff, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hdiff_nonneg]
  have hQratio : (nuttallQ 2 1 a b / (a : ℂ)).re =
      (∫ t in Ioi b, nuttallQ21RealKernel a t) / a := by
    rw [Complex.div_ofReal_re, hQb, Complex.ofReal_re]
  rw [theorem2TwoRowsCandidate_eq_amplitudeNormalizedIncrement
    lambda x hlambda]
  rw [hnorm_diff]
  rw [noncentralTwoRowAxialCDF_eq_one_sub_nuttallQ21 a x ha hx, hQratio]
  dsimp [b]
  field_simp [ha.ne']
  ring

/-- Theorem 1's `(1,2,1)` formula is now connected to the actual Wishart CDF
for every nonzero complex `2 × 1` mean matrix, not only for an axial choice.
The noncentrality parameter is the squared Frobenius norm of the mean. -/
theorem theorem1TwoRowsCandidate_eq_actualCDF
    (M : Matrix (Fin 2) (Fin 1) ℂ) (x : ℝ) (hx : 0 ≤ x)
    (hM : complexSampleMean M ≠ 0) :
    theorem1CdfCandidate 1 2 1 (by omega) (by omega)
        (fun _ : Fin 1 => ‖complexSampleMean M‖ ^ 2 / 2) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue M (by norm_num))) x := by
  let a : ℝ := ‖complexSampleMean M‖
  let lambda : ℝ := a ^ 2 / 2
  let b : ℝ := Real.sqrt (2 * x)
  have ha : 0 < a := by
    dsimp [a]
    exact norm_pos_iff.mpr hM
  have hb : 0 ≤ b := by dsimp [b]; exact Real.sqrt_nonneg _
  have hparam : Real.sqrt (2 * lambda) = a := by
    dsimp [lambda]
    rw [show 2 * (a ^ 2 / 2) = a ^ 2 by ring,
      Real.sqrt_sq_eq_abs, abs_of_nonneg (le_of_lt ha)]
  have hQb : nuttallQ 2 1 a b =
      (∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) :=
    nuttallQ21_eq_realIntegral a b ha.le hb
  have hQre : (nuttallQ 2 1 a b).re =
      ∫ t in Ioi b, nuttallQ21RealKernel a t := by
    rw [hQb, Complex.ofReal_re]
  have hQnorm : ‖nuttallQ 2 1 a b‖ =
      ∫ t in Ioi b, nuttallQ21RealKernel a t :=
    norm_nuttallQ21_eq_realIntegral a b ha.le hb
  have hratio : (nuttallQ 2 1 a b / (a : ℂ)).re =
      ‖nuttallQ 2 1 a b‖ / a := by
    rw [Complex.div_ofReal_re, hQre, hQnorm]
  rw [theorem1TwoRowsCandidate_eq_amplitudeNormalizedQ lambda x (by
    dsimp [lambda]
    positivity)]
  rw [hparam, noncentralTwoRowCDF_eq_meanNormNuttallQ M x hx hM]
  dsimp [theorem1TwoRowScalarQ]
  rw [hparam]
  simpa [theorem1TwoRowScalarQ, a, b] using
    congrArg (fun y : ℝ => 1 - y) hratio.symm

/-- Theorem 2's `(1,2,1)` formula likewise equals the actual CDF for every
nonzero complex `2 × 1` mean. In the one-column case the largest and smallest
eigenvalues are the same statistic. -/
theorem theorem2TwoRowsCandidate_eq_actualCDF
    (M : Matrix (Fin 2) (Fin 1) ℂ) (x : ℝ) (hx : 0 ≤ x)
    (hM : complexSampleMean M ≠ 0) :
    theorem2CdfCandidate 1 2 1 (by omega) (by omega)
        (fun _ : Fin 1 => ‖complexSampleMean M‖ ^ 2 / 2) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue M (by norm_num))) x := by
  let a : ℝ := ‖complexSampleMean M‖
  let lambda : ℝ := a ^ 2 / 2
  let b : ℝ := Real.sqrt (2 * x)
  have ha : 0 < a := by
    dsimp [a]
    exact norm_pos_iff.mpr hM
  have hb : 0 ≤ b := by dsimp [b]; exact Real.sqrt_nonneg _
  have hparam : Real.sqrt (2 * lambda) = a := by
    dsimp [lambda]
    rw [show 2 * (a ^ 2 / 2) = a ^ 2 by ring,
      Real.sqrt_sq_eq_abs, abs_of_nonneg (le_of_lt ha)]
  have htotal : ∫ t in Ioi (0 : ℝ), nuttallQ21RealKernel a t = a :=
    nuttallQ21RealIntegral_eq_amplitude a ha
  have hmono : ∫ t in Ioi b, nuttallQ21RealKernel a t ≤
      ∫ t in Ioi (0 : ℝ), nuttallQ21RealKernel a t := by
    apply setIntegral_mono_set (nuttallQ21RealKernel_integrableOn_Ioi a ha.le)
      ?_ (Ioi_subset_Ioi hb).eventuallySubset
    filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    exact nuttallQ21RealKernel_nonneg_of_nonneg ha.le (le_of_lt ht)
  have hQb : nuttallQ 2 1 a b =
      (∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) :=
    nuttallQ21_eq_realIntegral a b ha.le hb
  have hQ0 : nuttallQ 2 1 a 0 = (a : ℂ) :=
    nuttallQ21_zeroThreshold_eq_amplitude a ha
  have hdiff : nuttallQ 2 1 a 0 - nuttallQ 2 1 a b =
      ((a - ∫ t in Ioi b, nuttallQ21RealKernel a t : ℝ) : ℂ) := by
    rw [hQ0, hQb]
    push_cast
    rfl
  have hdiff_nonneg : 0 ≤ a - ∫ t in Ioi b, nuttallQ21RealKernel a t := by
    apply sub_nonneg.mpr
    calc
      (∫ t in Ioi b, nuttallQ21RealKernel a t) ≤
          ∫ t in Ioi (0 : ℝ), nuttallQ21RealKernel a t := hmono
      _ = a := htotal
  have hnorm_diff :
      ‖nuttallQ 2 1 a 0 - nuttallQ 2 1 a b‖ =
        a - ∫ t in Ioi b, nuttallQ21RealKernel a t := by
    rw [hdiff, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hdiff_nonneg]
  have hQre : (nuttallQ 2 1 a b).re =
      ∫ t in Ioi b, nuttallQ21RealKernel a t := by
    rw [hQb, Complex.ofReal_re]
  have hQratio : (nuttallQ 2 1 a b / (a : ℂ)).re =
      (∫ t in Ioi b, nuttallQ21RealKernel a t) / a := by
    rw [Complex.div_ofReal_re, hQre]
  rw [theorem2TwoRowsCandidate_eq_amplitudeNormalizedIncrement lambda x (by
    dsimp [lambda]
    positivity)]
  rw [hparam, hnorm_diff]
  rw [noncentralTwoRowCDF_eq_meanNormNuttallQ M x hx hM]
  dsimp [a, b]
  rw [hQratio]
  field_simp [ha.ne']
  ring

/-- The same one-column Theorem 2 result, with the statistic explicitly shown
as the largest (equivalently, unique) eigenvalue of the `1 × 1` Gram matrix. -/
theorem theorem2TwoRowsCandidate_eq_actualLargestCDF
    (M : Matrix (Fin 2) (Fin 1) ℂ) (x : ℝ) (hx : 0 ≤ x)
    (hM : complexSampleMean M ≠ 0) :
    theorem2CdfCandidate 1 2 1 (by omega) (by omega)
        (fun _ : Fin 1 => ‖complexSampleMean M‖ ^ 2 / 2) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (twoRowUniqueGramEigenvalue M)) x := by
  rw [theorem2TwoRowsCandidate_eq_actualCDF M x hx hM]
  congr 2

/-- At zero noncentrality the axial mean is the central model. The paper uses
its separate `L=0` branch, already matched to the actual two-row central
Wishart CDF. -/
theorem theorem1TwoRowsCentralCandidate_eq_actualCDF
    (x : ℝ) (hx : 0 ≤ x) :
    theorem1CdfCandidate 1 2 0 (by omega) (by omega)
        (fun j : Fin 0 => Fin.elim0 j) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue
          (twoRowAxialMean 0) (by norm_num))) x := by
  have hmean : twoRowAxialMean 0 =
      (0 : Matrix (Fin 2) (Fin 1) ℂ) := by
    ext i j
    fin_cases i <;> fin_cases j <;> simp [twoRowAxialMean]
  rw [hmean]
  exact theorem1CentralOneColumn_eq_sampleSmallestEigenvalueCDF
    2 (by omega) x hx

/-- The matching zero-noncentrality branch for Theorem 2. -/
theorem theorem2TwoRowsCentralCandidate_eq_actualCDF
    (x : ℝ) (hx : 0 ≤ x) :
    theorem2CdfCandidate 1 2 0 (by omega) (by omega)
        (fun j : Fin 0 => Fin.elim0 j) x =
      cdf ((stdGaussian (ComplexSample (m := 2) (n := 1))).map
        (complexNoncentralSampleSmallestEigenvalue
          (twoRowAxialMean 0) (by norm_num))) x := by
  have hmean : twoRowAxialMean 0 =
      (0 : Matrix (Fin 2) (Fin 1) ℂ) := by
    ext i j
    fin_cases i <;> fin_cases j <;> simp [twoRowAxialMean]
  rw [hmean]
  exact theorem2CentralOneColumn_eq_sampleSmallestEigenvalueCDF
    2 (by omega) x hx

end JinWishart
